# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      inputs:
        containerRegistry: 'testacrreg'
        command: 'login'
    - task: aquasecScanner@4
      inputs:
        image: '$(Build.BuildId)'
        scanType: 'local'
        register: false
        hideBase: false
        showNegligible: false
        windowsScannerVersion: '6.5.0'
        scanner: 'tstacraq.azurecr.io/ravindraannamtest/scanner6.5'
        connection: 'Aquascaner'
        scanMalware: true
    - task: Docker@2
      inputs:
                containerRegistry: 'testacrreg'
                repository: 'ravindraannamtest'
                command: 'push'
          
          
